### ISSUE TITLE
[3.2.0]+ `state.teardown is not a function`

### ISSUE THREAD

**Issue by boris-petrov** [ember-modifier/ember-modifier#250]
After updating from 3.1.0 to 3.2.1, I get a runtime exception:

```
Uncaught (in promise) TypeError: state.teardown is not a function
    at FunctionBasedModifierManager.destroyModifier (modifier-manager.js:75:1)
```

My modifier is pretty simple:

```ts
import { set } from '@ember/object';
import { modifier } from '@glint/environment-ember-loose/ember-modifier';
import type { ExtractFieldsOfType } from '...';

const refModifier = modifier(<T, U extends ExtractFieldsOfType<T, HTMLElement>>(element: Element & T[U], [context, property]: [T, U]) =>
  set(context, property, element),
);

export default refModifier;
```

The `state` variable in `destroyModifier` is:

```
element: a#ember322.ember-view
instance: (element, _ref) => {…}
teardown: a#ember322.ember-view
[[Prototype]]: Object
```

I.e. it has `teardown` but it's definitely not a function but rather some element. Any ideas?

**Comment by chriskrycho** [comment]
Fix released in [v3.2.2](https://github.com/ember-modifier/ember-modifier/releases/tag/v3.2.2).
